version: 2.1

orbs:
  heroku: circleci/heroku@1.2.5

workflows:
  version: 2.1
  Check, Build and Test:
    jobs:
      - Static Analysis
      - Build
      - Test:
          requires:
            - Build

  Deploy:
    jobs:
      - Trigger Deploy:
          type: approval
          filters:
            branches:
              only: /.*/

      - Deploy to Heroku:
          requires:
            - Trigger Deploy

jobs:
  Static Analysis:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - run: gradle ktlintCheck
      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

  Build:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Load dependencies
          command: gradle dependencies

      - save_cache:
          name: Execute build script
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle.kts" }}

      - run:
          name: Build Jar
          command: gradle bootJar

  Test:
    docker:
      - image: circleci/openjdk:11-jdk

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle.kts" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Run tests
          command: gradle test

  Deploy to Heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
